
IF
    GlobalGT("C0KvelBegin","GLOBAL",15)
    GlobalLT("C0KvelBegin","GLOBAL",18)
THEN
    RESPONSE #100
        SetGlobal("C0KvelBegin","GLOBAL",18)
	    MoveGlobal("%bg1_eet_symbol%0705","C0KVEL",[596.440])
		ActionOverride("C0KVEL",Face(SE))
	    CreateCreature("C0KVNP01",[597.500],SW)
		SmallWait(1)
		ActionOverride("C0KVEL",DestroyItem("DAGG05"))
END

IF
	InMyArea(Player1)
    Global("C0KvelBegin","GLOBAL",20)
	NumDeadGT("C0KVNP08",1)
THEN
    RESPONSE #100
		Wait(1)
		SetGlobal("C0KvelBegin","GLOBAL",21)
		ClearAllActions()
		StartCutSceneMode()
		StartCutScene("C0KVC03")
END