IF
	Global("C0KvelBegin","GLOBAL",14)
	!See("C0KVEL")
THEN
RESPONSE #100
	StartDialogNoSet(Player1)
	Continue()
END

IF
	Global("C0KvelBegin","GLOBAL",16)
THEN
RESPONSE #100
	SetGlobal("C0KvelBegin","GLOBAL",17)
	    MoveGlobal("%bg1_eet_symbol%4809","C0KVEL",[238.239])
		ActionOverride("C0KVEL",Face(NW))
	Continue()
END

IF
	AreaCheck("%bg1_eet_symbol%4809")
	!BeenInParty("C0KVEL")
	GlobalGT("Chapter","GLOBAL",%tutu_chapter_3%)
THEN
RESPONSE #100
	DestroySelf()
	Continue()
END

IF
	Allegiance(Myself,NEUTRAL)
	!InParty("C0KVEL")
    Allegiance("C0KVEL",ENEMY)
THEN
    RESPONSE #100
		Enemy()
END
